export const mockData = [
  {
    PDFName: '130000027866-6-A-ES-AGHS-20171213162833.pdf',
    SpecificationID: '50000016',
    Language: 'ES',
    GENVARIANT: 'US-MSDS',
    ProductName: 'CORAGEN SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-6-A',
    LegacySDSID: '130000027866-6-A',
    RevisionDate: '10-15-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'AGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-A-BE-EGHS-20171213162830.pdf',
    SpecificationID: '50000016',
    Language: 'BE',
    GENVARIANT: 'US-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-A',
    LegacySDSID: '130000027866-A',
    RevisionDate: '08-28-17',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-A-FR-EGHS-20171213162830.pdf',
    SpecificationID: '50000016',
    Language: 'FR',
    GENVARIANT: 'US-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-A',
    LegacySDSID: '130000027866-A',
    RevisionDate: '04-25-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-AR-A-ES-AGHS-20171213162826.pdf',
    SpecificationID: '50000016',
    Language: 'ES',
    GENVARIANT: 'AR-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-AR-A',
    LegacySDSID: '130000027866-AR-A',
    RevisionDate: '08-26-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'AGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-AT-A-AT-EGHS-20171213162827.pdf',
    SpecificationID: '50000016',
    Language: 'AT',
    GENVARIANT: 'AT-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-AT-A',
    LegacySDSID: '130000027866-AT-A',
    RevisionDate: '01-14-14',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-AU-5-A-EN-ASAP-20171213162827.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'AU-MSDS',
    ProductName: 'CORAGEN INSECTICIDE',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN INSECTICIDE',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '0',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-AU-5-A',
    LegacySDSID: '130000027866-AU-5-A',
    RevisionDate: '11-12-15',
    WercsRevisionNo: '1',
    WercsSubFormat: 'ASAP',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-AU-5-A-EN-ASAP-201810110327.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'AU-MSDS',
    ProductName: 'CORAGEN INSECTICIDE',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN INSECTICIDE',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '10-01-18',
    ActiveVersion: '0',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-AU-5-A',
    LegacySDSID: '130000027866-AU-5-A',
    RevisionDate: '03-01-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'ASAP',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-AU-5-A-EN-ASAP-2018127162634.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'AU-MSDS',
    ProductName: 'CORAGEN INSECTICIDE',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN INSECTICIDE',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-07-18',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-AU-5-A',
    LegacySDSID: '130000027866-AU-5-A',
    RevisionDate: '03-01-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'ASAP',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-BE_FR-A-BF-EGHS-201946134212.pdf',
    SpecificationID: '50000016',
    Language: 'BF',
    GENVARIANT: 'FR-MSDS',
    ProductName: 'Coragen',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'Coragen',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '04-06-19',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-BE_FR-A',
    LegacySDSID: '130000027866-BE_FR-A',
    RevisionDate: '01-01-19',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'EXTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-BE-A-BD-EGHS-20171213162827.pdf',
    SpecificationID: '50000016',
    Language: 'BD',
    GENVARIANT: 'BE-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-BE-A',
    LegacySDSID: '130000027866-BE-A',
    RevisionDate: '03-31-15',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-BE-A-BF-EGHS-20171213162827.pdf',
    SpecificationID: '50000016',
    Language: 'BF',
    GENVARIANT: 'BE-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-BE-A',
    LegacySDSID: '130000027866-BE-A',
    RevisionDate: '08-04-15',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-BE-A-DE-EGHS-20171213162827.pdf',
    SpecificationID: '50000016',
    Language: 'DE',
    GENVARIANT: 'BE-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-BE-A',
    LegacySDSID: '130000027866-BE-A',
    RevisionDate: '08-04-15',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-BG-2-A-BG-EGHS-20171213162828.pdf',
    SpecificationID: '50000016',
    Language: 'BG',
    GENVARIANT: 'BG-MSDS',
    ProductName: 'CORAGEN 20 SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN 20 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-BG-2-A',
    LegacySDSID: '130000027866-BG-2-A',
    RevisionDate: '11-13-17',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-BO-A-MS-ASLA-2018119143219.pdf',
    SpecificationID: '50000016',
    Language: 'MS',
    GENVARIANT: 'BO-MSDS',
    ProductName: 'CORAGEN SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '11-09-18',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-BO-A',
    LegacySDSID: '130000027866-BO-A',
    RevisionDate: '11-20-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'ASLA',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-CA-A-CF-AGHS-2018111985920.pdf',
    SpecificationID: '50000016',
    Language: 'CF',
    GENVARIANT: 'CA-MSDS',
    ProductName: 'Coragen Insecticide',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'Coragen Insecticide',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '11-19-18',
    ActiveVersion: '0',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-CA-A',
    LegacySDSID: '130000027866-CA-A',
    RevisionDate: '03-01-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'AGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-CA-A-CF-AGHS-201921135810.pdf',
    SpecificationID: '50000016',
    Language: 'CF',
    GENVARIANT: 'CA-MSDS',
    ProductName: 'Coragen Insecticide',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'Coragen Insecticide',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '02-01-19',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-CA-A',
    LegacySDSID: '130000027866-CA-A',
    RevisionDate: '03-01-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'AGHS',
    AuthorizedPortal: 'EXTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-CA-A-EN-AGHS-2018111985920.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'CA-MSDS',
    ProductName: 'Coragen Insecticide',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'Coragen Insecticide',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '11-19-18',
    ActiveVersion: '0',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-CA-A',
    LegacySDSID: '130000027866-CA-A',
    RevisionDate: '03-01-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'AGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-CA-A-EN-AGHS-201921135811.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'CA-MSDS',
    ProductName: 'Coragen Insecticide',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'Coragen Insecticide',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '02-01-19',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-CA-A',
    LegacySDSID: '130000027866-CA-A',
    RevisionDate: '03-01-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'AGHS',
    AuthorizedPortal: 'EXTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-CH-A-SF-EGHS-20171213162838.pdf',
    SpecificationID: '50000016',
    Language: 'SF',
    GENVARIANT: 'CH-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-CH-A',
    LegacySDSID: '130000027866-CH-A',
    RevisionDate: '02-23-17',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-CH-A-SG-EGHS-20171213162838.pdf',
    SpecificationID: '50000016',
    Language: 'SG',
    GENVARIANT: 'CH-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-CH-A',
    LegacySDSID: '130000027866-CH-A',
    RevisionDate: '02-23-17',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-CH-A-SI-EGHS-20171213162839.pdf',
    SpecificationID: '50000016',
    Language: 'SI',
    GENVARIANT: 'CH-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-CH-A',
    LegacySDSID: '130000027866-CH-A',
    RevisionDate: '02-23-17',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-CN-3-A-CN-ASAP-20171213162829.pdf',
    SpecificationID: '50000016',
    Language: 'CN',
    GENVARIANT: 'CN-MSDS',
    ProductName: 'CORAGEN 200 SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN 200 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '0',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-CN-3-A',
    LegacySDSID: '130000027866-CN-3-A',
    RevisionDate: '07-15-14',
    WercsRevisionNo: '1',
    WercsSubFormat: 'ASAP',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-CN-3-A-CN-ASAP-201810110342.pdf',
    SpecificationID: '50000016',
    Language: 'CN',
    GENVARIANT: 'CN-MSDS',
    ProductName: 'CORAGEN 200 SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN 200 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '10-01-18',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-CN-3-A',
    LegacySDSID: '130000027866-CN-3-A',
    RevisionDate: '03-01-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'ASAP',
    AuthorizedPortal: 'EXTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-CN-3-A-EN-ASAP-20171213162829.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'CN-MSDS',
    ProductName: 'CORAGEN 200 SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN 200 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '0',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-CN-3-A',
    LegacySDSID: '130000027866-CN-3-A',
    RevisionDate: '07-15-14',
    WercsRevisionNo: '1',
    WercsSubFormat: 'ASAP',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-CN-3-A-EN-ASAP-2018101102218.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'CN-MSDS',
    ProductName: 'CORAGEN 200 SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN 200 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '10-01-18',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-CN-3-A',
    LegacySDSID: '130000027866-CN-3-A',
    RevisionDate: '03-01-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'ASAP',
    AuthorizedPortal: 'EXTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-CY-6-A-EL-EGHS-20171213162829.pdf',
    SpecificationID: '50000016',
    Language: 'EL',
    GENVARIANT: 'CY-MSDS',
    ProductName: 'CORAGEN SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-CY-6-A',
    LegacySDSID: '130000027866-CY-6-A',
    RevisionDate: '02-24-17',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-CZ-2-A-CS-EGHS-20171213162829.pdf',
    SpecificationID: '50000016',
    Language: 'CS',
    GENVARIANT: 'CZ-MSDS',
    ProductName: 'CORAGEN 20 SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN 20 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-CZ-2-A',
    LegacySDSID: '130000027866-CZ-2-A',
    RevisionDate: '03-31-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-CZ-A-EN-EGHS-20171213162830.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'CZ-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-CZ-A',
    LegacySDSID: '130000027866-CZ-A',
    RevisionDate: '03-31-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-DE-A-DE-EGHS-20171213162831.pdf',
    SpecificationID: '50000016',
    Language: 'DE',
    GENVARIANT: 'DE-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-DE-A',
    LegacySDSID: '130000027866-DE-A',
    RevisionDate: '09-11-15',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-DE-A-EN-EGHS-20171213162831.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'DE-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-DE-A',
    LegacySDSID: '130000027866-DE-A',
    RevisionDate: '09-11-15',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-ES-2-A-ES-EGHS-20171213162837.pdf',
    SpecificationID: '50000016',
    Language: 'ES',
    GENVARIANT: 'ES-MSDS',
    ProductName: 'CORAGEN 20 SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN 20 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-ES-2-A',
    LegacySDSID: '130000027866-ES-2-A',
    RevisionDate: '08-17-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-EU-A-EN-EGHS-201953115251.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'EU-MSDS',
    ProductName: 'Coragen 20 SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'Coragen 20 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '05-31-19',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-EU-A',
    LegacySDSID: '130000027866-EU-A',
    RevisionDate: '06-01-18',
    WercsRevisionNo: '2',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'EXTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-FI-2-A-FI-EGHS-20171213162831.pdf',
    SpecificationID: '50000016',
    Language: 'FI',
    GENVARIANT: 'FI-MSDS',
    ProductName: 'CORAGEN 20 SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN 20 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-FI-2-A',
    LegacySDSID: '130000027866-FI-2-A',
    RevisionDate: '10-13-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-FR-A-FR-EGHS-20171213162831.pdf',
    SpecificationID: '50000016',
    Language: 'FR',
    GENVARIANT: 'FR-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-FR-A',
    LegacySDSID: '130000027866-FR-A',
    RevisionDate: '04-22-14',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-GB-A-BE-EGHS-20171213162831.pdf',
    SpecificationID: '50000016',
    Language: 'BE',
    GENVARIANT: 'GB-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-GB-A',
    LegacySDSID: '130000027866-GB-A',
    RevisionDate: '01-05-15',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-GR-A-EL-EGHS-20171213162832.pdf',
    SpecificationID: '50000016',
    Language: 'EL',
    GENVARIANT: 'GR-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-GR-A',
    LegacySDSID: '130000027866-GR-A',
    RevisionDate: '11-12-15',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-GR-A-EN-EGHS-20171213162832.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'GR-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-GR-A',
    LegacySDSID: '130000027866-GR-A',
    RevisionDate: '11-12-15',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-IE-A-EN-EGHS-20171213162832.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'IE-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-IE-A',
    LegacySDSID: '130000027866-IE-A',
    RevisionDate: '12-09-14',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-IN-A-EN-ASAP-20171213162832.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'IN-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-IN-A',
    LegacySDSID: '130000027866-IN-A',
    RevisionDate: '01-30-17',
    WercsRevisionNo: '1',
    WercsSubFormat: 'ASAP',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-LU-A-DE-EGHS-20171213162833.pdf',
    SpecificationID: '50000016',
    Language: 'DE',
    GENVARIANT: 'LU-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-LU-A',
    LegacySDSID: '130000027866-LU-A',
    RevisionDate: '09-02-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-LU-A-FR-EGHS-20171213162833.pdf',
    SpecificationID: '50000016',
    Language: 'FR',
    GENVARIANT: 'LU-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-LU-A',
    LegacySDSID: '130000027866-LU-A',
    RevisionDate: '09-02-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-MX-A-EN-ASLA-2017121813724.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'MX-MSDS',
    ProductName: 'CORAGEN',
    // tslint:disable-next-line:max-line-length
    ChemicalName: 'CHLORANTRANILIPROLE: 3-bromo-4â€²-chloro-1-(3-chloro-2-pyridyl)-2â€²-methyl-6â€²-(methylcarbamoyl)pyrazole-5-carboxanilide (IUPAC name); 3-bromo-N-[4-chloro-2-methyl-6-[(methylamino)carbonyl]phenyl]-1-(3-chloro-2-pyridinyl)-1H-pyrazole-5-carboxamide (CAS name',
    CommonName: 'Chlorantraniliprole',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-18-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-MX-A',
    LegacySDSID: '130000027866-MX-A',
    RevisionDate: '05-27-15',
    WercsRevisionNo: '1',
    WercsSubFormat: 'ASLA',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-MX-A-MS-AGHS-20185815481.pdf',
    SpecificationID: '50000016',
    Language: 'MS',
    GENVARIANT: 'MX-MSDS',
    ProductName: 'CORAGEN 20 SC',
    // tslint:disable-next-line:max-line-length
    ChemicalName: 'CLORANTRANILIPROL: 3-bromo-4\'-cloro-1- (3-cloro-2-piridil) -2\'-metil-6 \'- (metilcarbamoil) pirazol-5-carboxanilida (nombre IUPAC); 3-bromo-N- [4-cloro-2-metil-6 - [(metilamino) carbonil] fenil] -1- (3-cloro-2-piridinil) -1H-pirazol-5-carboxamida (nombre C',
    CommonName: 'Clorantraniliprol',
    TradeName: 'CORAGEN 20 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '05-08-18',
    ActiveVersion: '0',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-MX-A',
    LegacySDSID: '130000027866-MX-A',
    RevisionDate: '05-07-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'AGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-MX-A-MS-AGHS-201859142019.pdf',
    SpecificationID: '50000016',
    Language: 'MS',
    GENVARIANT: 'MX-MSDS',
    ProductName: 'CORAGEN 20 SC',
    // tslint:disable-next-line:max-line-length
    ChemicalName: 'CLORANTRANILIPROL: 3-bromo-4\'-cloro-1- (3-cloro-2-piridil) -2\'-metil-6 \'- (metilcarbamoil) pirazol-5-carboxanilida (nombre IUPAC); 3-bromo-N- [4-cloro-2-metil-6 - [(metilamino) carbonil] fenil] -1- (3-cloro-2-piridinil) -1H-pirazol-5-carboxamida (nombre C',
    CommonName: 'Clorantraniliprol',
    TradeName: 'CORAGEN 20 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '05-09-18',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-MX-A',
    LegacySDSID: '130000027866-MX-A',
    RevisionDate: '05-07-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'AGHS',
    AuthorizedPortal: 'EXTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-NL-A-NL-EGHS-20171213162839.pdf',
    SpecificationID: '50000016',
    Language: 'NL',
    GENVARIANT: 'NL-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-NL-A',
    LegacySDSID: '130000027866-NL-A',
    RevisionDate: '09-14-15',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-NZ-5-A-EN-ASAP-20171213162834.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'NZ-MSDS',
    ProductName: 'CORAGEN INSECTICIDE',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN INSECTICIDE',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '0',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-NZ-5-A',
    LegacySDSID: '130000027866-NZ-5-A',
    RevisionDate: '09-23-15',
    WercsRevisionNo: '1',
    WercsSubFormat: 'ASAP',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-NZ-5-A-EN-ASAP-201810110334.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'NZ-MSDS',
    ProductName: 'CORAGEN INSECTICIDE',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN INSECTICIDE',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '10-01-18',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-NZ-5-A',
    LegacySDSID: '130000027866-NZ-5-A',
    RevisionDate: '03-01-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'ASAP',
    AuthorizedPortal: 'EXTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-PL-3-A-PL-EGHS-20171213162834.pdf',
    SpecificationID: '50000016',
    Language: 'PL',
    GENVARIANT: 'PL-MSDS',
    ProductName: 'CORAGEN 200 SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN 200 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-PL-3-A',
    LegacySDSID: '130000027866-PL-3-A',
    RevisionDate: '02-18-15',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-PL-A-EN-EGHS-20171213162834.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'PL-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-PL-A',
    LegacySDSID: '130000027866-PL-A',
    RevisionDate: '02-18-15',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-PT-A-PT-EGHS-20171213162835.pdf',
    SpecificationID: '50000016',
    Language: 'PT',
    GENVARIANT: 'PT-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-PT-A',
    LegacySDSID: '130000027866-PT-A',
    RevisionDate: '07-11-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-PY-A-MS-ASLA-2018119143214.pdf',
    SpecificationID: '50000016',
    Language: 'MS',
    GENVARIANT: 'PY-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '11-09-18',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-PY-A',
    LegacySDSID: '130000027866-PY-A',
    RevisionDate: '03-01-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'ASLA',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-RO-A-EN-EGHS-20171213162835.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'RO-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-RO-A',
    LegacySDSID: '130000027866-RO-A',
    RevisionDate: '03-21-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-RO-A-RO-EGHS-20171213162835.pdf',
    SpecificationID: '50000016',
    Language: 'RO',
    GENVARIANT: 'RO-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-RO-A',
    LegacySDSID: '130000027866-RO-A',
    RevisionDate: '06-29-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-RS-A-EN-EGHS-20171213162836.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'RS-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-RS-A',
    LegacySDSID: '130000027866-RS-A',
    RevisionDate: '03-17-15',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-RS-A-SR-EGHS-20171213162836.pdf',
    SpecificationID: '50000016',
    Language: 'SR',
    GENVARIANT: 'RS-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-RS-A',
    LegacySDSID: '130000027866-RS-A',
    RevisionDate: '03-17-15',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-RU-A-RU-EGHS-20171213162836.pdf',
    SpecificationID: '50000016',
    Language: 'RU',
    GENVARIANT: 'RU-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-RU-A',
    LegacySDSID: '130000027866-RU-A',
    RevisionDate: '10-21-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-SE-A-SV-EGHS-2018102984157.pdf',
    SpecificationID: '50000016',
    Language: 'SV',
    GENVARIANT: 'SE-MSDS',
    ProductName: 'Coragenï¿½ 20 SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'Coragenï¿½ 20 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '10-29-18',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-SE-A',
    LegacySDSID: '130000027866-SE-A',
    RevisionDate: '12-10-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-SG-A-EN-ASAP-2019531152524.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'SG-MSDS',
    ProductName: 'Coragen 20 SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'Coragen 20 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '05-31-19',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-SG-A',
    LegacySDSID: '130000027866-SG-A',
    RevisionDate: '05-22-19',
    WercsRevisionNo: '1.1000000000000001',
    WercsSubFormat: 'ASAP',
    AuthorizedPortal: 'EXTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-SI-A-EN-EGHS-20171213162837.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'SI-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-SI-A',
    LegacySDSID: '130000027866-SI-A',
    RevisionDate: '07-13-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-SI-A-SN-EGHS-20171213162837.pdf',
    SpecificationID: '50000016',
    Language: 'SN',
    GENVARIANT: 'SI-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-SI-A',
    LegacySDSID: '130000027866-SI-A',
    RevisionDate: '07-13-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-SK-2-A-SK-EGHS-20171213162836.pdf',
    SpecificationID: '50000016',
    Language: 'SK',
    GENVARIANT: 'SK-MSDS',
    ProductName: 'CORAGEN 20 SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN 20 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-SK-2-A',
    LegacySDSID: '130000027866-SK-2-A',
    RevisionDate: '02-16-17',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-TR-2-A-TR-EGHS-20171213162839.pdf',
    SpecificationID: '50000016',
    Language: 'TR',
    GENVARIANT: 'TR-MSDS',
    ProductName: 'CORAGEN 20 SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN 20 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-TR-2-A',
    LegacySDSID: '130000027866-TR-2-A',
    RevisionDate: '06-01-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-TW-A-CN-ASAP-20171213162839.pdf',
    SpecificationID: '50000016',
    Language: 'CN',
    GENVARIANT: 'TW-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '0',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-TW-A',
    LegacySDSID: '130000027866-TW-A',
    RevisionDate: '02-04-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'ASAP',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-TW-A-CN-ASAP-2018104101317.pdf',
    SpecificationID: '50000016',
    Language: 'CN',
    GENVARIANT: 'TW-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '10-04-18',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-TW-A',
    LegacySDSID: '130000027866-TW-A',
    RevisionDate: '12-07-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'ASAP',
    AuthorizedPortal: 'EXTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-TW-A-EN-ASAP-20171213162839.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'TW-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '0',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-TW-A',
    LegacySDSID: '130000027866-TW-A',
    RevisionDate: '02-04-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'ASAP',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-TW-A-EN-ASAP-2018104101317.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'TW-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '10-04-18',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-TW-A',
    LegacySDSID: '130000027866-TW-A',
    RevisionDate: '12-07-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'ASAP',
    AuthorizedPortal: 'EXTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-US-4-A-EN-AGHS-20171213162840.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'US-MSDS',
    ProductName: 'CORAGEN INSECT CONTROL',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN INSECT CONTROL',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-US-4-A',
    LegacySDSID: '130000027866-US-4-A',
    RevisionDate: '05-27-15',
    WercsRevisionNo: '1',
    WercsSubFormat: 'AGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-US-A-DE-AGHS-20171213162840.pdf',
    SpecificationID: '50000016',
    Language: 'DE',
    GENVARIANT: 'US-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-US-A',
    LegacySDSID: '130000027866-US-A',
    RevisionDate: '03-23-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'AGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000027866-ZA-A-EN-EGHS-20171213162837.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'ZA-MSDS',
    ProductName: 'CORAGEN',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'CORAGEN',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000027866-ZA-A',
    LegacySDSID: '130000027866-ZA-A',
    RevisionDate: '06-08-17',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '130000036158-AR-1-A-EN-AGHS-20171213162921.pdf',
    SpecificationID: '50000016',
    Language: 'EN',
    GENVARIANT: 'AR-MSDS',
    ProductName: 'AMICOR',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'AMICOR',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-13-17',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '130000036158-AR-1-A',
    LegacySDSID: '130000036158-AR-1-A',
    RevisionDate: '10-14-16',
    WercsRevisionNo: '1',
    WercsSubFormat: 'AGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '6044-1-A-EN-AGHS-201832716633.pdf',
    SpecificationID: '50000162',
    Language: 'EN',
    GENVARIANT: 'US-MSDS',
    ProductName: 'Cadusafos 200CS',
    ChemicalName: 'CADUSAFOS: S',
    CommonName: 'S-di-sec-butyl O-ethyl phosphorodithioate (IUPAC name); O-ethyl S',
    TradeName: 'S-bis(1-methylpropyl) phosphorodithioate (CAS Name)',
    CasNumber: 'Cadusafos',
    CommercialNames: 'Cadusafos 200CS',
    CMR: '',
    PublishDate: 'ApacheÂ® ',
    ActiveVersion: '',
    IUPAC: '03-27-18',
    INCODE: '0',
    EHSVersionNo: '',
    FMCBusiness: '',
    FileFormat: '',
    ValidityArea: 'FMC',
    ValidityAreaDescription: 'PDF',
    LegacySpecID: '',
    LegacySDSID: '',
    RevisionDate: '6044-1-A',
    WercsRevisionNo: '6044-1-A',
    WercsSubFormat: '03-27-18',
    AuthorizedPortal: '1',
    Path: 'AGHS'
  },
  {
    PDFName: '6044-1-A-EN-AGHS-2018412144227.pdf',
    SpecificationID: '50000162',
    Language: 'EN',
    GENVARIANT: 'US-MSDS',
    ProductName: 'Cadusafos 200CS',
    ChemicalName: 'CADUSAFOS: S',
    CommonName: 'S-di-sec-butyl O-ethyl phosphorodithioate (IUPAC name); O-ethyl S',
    TradeName: 'S-bis(1-methylpropyl) phosphorodithioate (CAS Name)',
    CasNumber: 'Cadusafos',
    CommercialNames: 'Cadusafos 200CS',
    CMR: '',
    PublishDate: 'ApacheÂ® ',
    ActiveVersion: '',
    IUPAC: '04-12-18',
    INCODE: '1',
    EHSVersionNo: '',
    FMCBusiness: '',
    FileFormat: '',
    ValidityArea: 'FMC',
    ValidityAreaDescription: 'PDF',
    LegacySpecID: '',
    LegacySDSID: '',
    RevisionDate: '6044-1-A',
    WercsRevisionNo: '6044-1-A',
    WercsSubFormat: '04-12-18',
    AuthorizedPortal: '1.01',
    Path: 'AGHS'
  },
  {
    PDFName: '6044-1-A-ID-AGHS-201832715560.pdf',
    SpecificationID: '50000162',
    Language: 'ID',
    GENVARIANT: 'ID_MSDS',
    ProductName: 'Cadusafos 200CS',
    ChemicalName: 'CADUSAFOS: S',
    CommonName: 'S-di-sec-butyl O-ethyl phosphorodithioate (IUPAC name); O-ethyl S',
    TradeName: 'S-bis(1-methylpropyl) phosphorodithioate (CAS Name)',
    CasNumber: 'Cadusafos',
    CommercialNames: 'Cadusafos 200CS',
    CMR: '',
    PublishDate: 'ApacheÂ® ',
    ActiveVersion: '',
    IUPAC: '03-27-18',
    INCODE: '0',
    EHSVersionNo: '',
    FMCBusiness: '',
    FileFormat: '',
    ValidityArea: 'FMC',
    ValidityAreaDescription: 'PDF',
    LegacySpecID: '',
    LegacySDSID: '',
    RevisionDate: '6044-1-A',
    WercsRevisionNo: '6044-1-A',
    WercsSubFormat: '03-27-18',
    AuthorizedPortal: '1',
    Path: 'AGHS'
  },
  {
    PDFName: '6044-1-A-ID-AGHS-2018412145550.pdf',
    SpecificationID: '50000162',
    Language: 'ID',
    GENVARIANT: 'ID_MSDS',
    ProductName: 'Cadusafos 200CS',
    ChemicalName: 'CADUSAFOS: S',
    CommonName: 'S-di-sec-butyl O-ethyl phosphorodithioate (IUPAC name); O-ethyl S',
    TradeName: 'S-bis(1-methylpropyl) phosphorodithioate (CAS Name)',
    CasNumber: 'Cadusafos',
    CommercialNames: 'Cadusafos 200CS',
    CMR: '',
    PublishDate: 'ApacheÂ® ',
    ActiveVersion: '',
    IUPAC: '04-12-18',
    INCODE: '1',
    EHSVersionNo: '',
    FMCBusiness: '',
    FileFormat: '',
    ValidityArea: 'FMC',
    ValidityAreaDescription: 'PDF',
    LegacySpecID: '',
    LegacySDSID: '',
    RevisionDate: '6044-1-A',
    WercsRevisionNo: '6044-1-A',
    WercsSubFormat: '04-12-18',
    AuthorizedPortal: '1.02',
    Path: 'AGHS'
  },
  {
    PDFName: '6044-1-A-KO-AGAP-201418135329.pdf',
    SpecificationID: '50000162',
    Language: 'KO',
    GENVARIANT: 'KO_MSDS',
    ProductName: 'Cadusafos 200CS',
    ChemicalName: 'FMC 67825; S',
    CommonName: 'S-di-sec-butyl O-ethyl phosphorodithioate; O-ethyl S',
    TradeName: 'S-bis(1-methylpropyl) phosphorodithioate',
    CasNumber: 'ì¹´ë‘ì‚¬í¬ìŠ¤',
    CommercialNames: 'Cadusafos 200CS',
    CMR: '',
    PublishDate: 'ApacheÂ® ',
    ActiveVersion: '',
    IUPAC: '01-08-14',
    INCODE: '0',
    EHSVersionNo: '',
    FMCBusiness: '',
    FileFormat: '',
    ValidityArea: 'FMC',
    ValidityAreaDescription: 'PDF',
    LegacySpecID: '',
    LegacySDSID: '',
    RevisionDate: '6044-1-A',
    WercsRevisionNo: '6044-1-A',
    WercsSubFormat: '01-08-14',
    AuthorizedPortal: '2',
    Path: 'AGAP'
  },
  {
    PDFName: '6044-1-A-KO-AGAP-201661144323.pdf',
    SpecificationID: '50000162',
    Language: 'KO',
    GENVARIANT: 'KO_MSDS',
    ProductName: 'Cadusafos 200CS',
    ChemicalName: 'FMC 67825; S',
    CommonName: 'S-di-sec-butyl O-ethyl phosphorodithioate; O-ethyl S',
    TradeName: 'S-bis(1-methylpropyl) phosphorodithioate',
    CasNumber: 'ì¹´ë‘ì‚¬í¬ìŠ¤',
    CommercialNames: 'Cadusafos 200CS',
    CMR: '',
    PublishDate: 'ApacheÂ® ',
    ActiveVersion: '',
    IUPAC: '06-01-16',
    INCODE: '1',
    EHSVersionNo: '',
    FMCBusiness: '',
    FileFormat: '',
    ValidityArea: 'FMC',
    ValidityAreaDescription: 'PDF',
    LegacySpecID: '',
    LegacySDSID: '',
    RevisionDate: '6044-1-A',
    WercsRevisionNo: '6044-1-A',
    WercsSubFormat: '06-01-16',
    AuthorizedPortal: '2.02',
    Path: 'AGAP'
  },
  {
    PDFName: '6044-A-MS-AGHS-201829142211.pdf',
    SpecificationID: '50000162',
    Language: 'MS',
    GENVARIANT: 'US-MSDS',
    ProductName: 'Rugby|TS 200 CS',
    ChemicalName: 'CADUSAFOS: S',
    CommonName: 'S-di-sec-butil O-etil fosforoditioato (IUPAC nombre); O-etil S',
    TradeName: 'S-bis(1-metilpropil) fosforoditioato (CAS nombre)',
    CasNumber: 'Cadusafos',
    CommercialNames: 'Rugby|TS 200 CS',
    CMR: '',
    PublishDate: '',
    ActiveVersion: '',
    IUPAC: '02-09-18',
    INCODE: '0',
    EHSVersionNo: '',
    FMCBusiness: '',
    FileFormat: '',
    ValidityArea: 'FMC',
    ValidityAreaDescription: 'PDF',
    LegacySpecID: '',
    LegacySDSID: '',
    RevisionDate: '6044-A',
    WercsRevisionNo: '6044-A',
    WercsSubFormat: '02-09-18',
    AuthorizedPortal: '1.04',
    Path: 'AGHS'
  },
  {
    PDFName: '6044-A-MS-AGHS-2018412143523.pdf',
    SpecificationID: '50000162',
    Language: 'MS',
    GENVARIANT: 'US-MSDS',
    ProductName: 'Rugby|TS 200 CS',
    ChemicalName: 'CADUSAFOS: S',
    CommonName: 'S-di-sec-butil O-etil fosforoditioato (IUPAC nombre); O-etil S',
    TradeName: 'S-bis(1-metilpropil) fosforoditioato (CAS nombre)',
    CasNumber: 'Cadusafos',
    CommercialNames: 'Rugby|TS 200 CS',
    CMR: '',
    PublishDate: '',
    ActiveVersion: '',
    IUPAC: '04-12-18',
    INCODE: '1',
    EHSVersionNo: '',
    FMCBusiness: '',
    FileFormat: '',
    ValidityArea: 'FMC',
    ValidityAreaDescription: 'PDF',
    LegacySpecID: '',
    LegacySDSID: '',
    RevisionDate: '6044-A',
    WercsRevisionNo: '6044-A',
    WercsSubFormat: '04-12-18',
    AuthorizedPortal: '1.05',
    Path: 'AGHS'
  },
  {
    PDFName: '6044-CH-A-EN-EGHS-20181220111747.pdf',
    SpecificationID: '50000162',
    Language: 'EN',
    GENVARIANT: 'CH-MSDS',
    ProductName: 'Rugby 200 CS',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'Rugby 200 CS',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '12-20-18',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '6044-CH-A',
    LegacySDSID: '6044-CH-A',
    RevisionDate: '11-01-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'EGHS',
    AuthorizedPortal: 'EXTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '6044-MX-A-EN-AGHS-2018412155111.pdf',
    SpecificationID: '50000162',
    Language: 'EN',
    GENVARIANT: 'MX-MSDS',
    ProductName: 'Rugby 200 CS',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'Rugby 200 CS',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '04-12-18',
    ActiveVersion: '0',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '6044-MX-A',
    LegacySDSID: '6044-MX-A',
    RevisionDate: '04-12-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'AGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '6044-MX-A-EN-AGHS-201841315828.pdf',
    SpecificationID: '50000162',
    Language: 'EN',
    GENVARIANT: 'MX-MSDS',
    ProductName: 'Rugby 200 CS',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'Rugby 200 CS',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '04-13-18',
    ActiveVersion: '0',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '6044-MX-A',
    LegacySDSID: '6044-MX-A',
    RevisionDate: '04-12-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'AGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '6044-MX-A-EN-AGHS-2018420155749.pdf',
    SpecificationID: '50000162',
    Language: 'EN',
    GENVARIANT: 'MX-MSDS',
    ProductName: 'Rugby 200 SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'Rugby 200 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '04-20-18',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '6044-MX-A',
    LegacySDSID: '6044-MX-A',
    RevisionDate: '04-12-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'AGHS',
    AuthorizedPortal: 'EXTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '6044-MX-A-MS-AGHS-2018413151725.pdf',
    SpecificationID: '50000162',
    Language: 'MS',
    GENVARIANT: 'MX-MSDS',
    ProductName: 'Rugby 200 SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'Rugby 200 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '04-13-18',
    ActiveVersion: '0',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '6044-MX-A',
    LegacySDSID: '6044-MX-A',
    RevisionDate: '04-12-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'AGHS',
    AuthorizedPortal: 'INTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  },
  {
    PDFName: '6044-MX-A-MS-AGHS-201841614240.pdf',
    SpecificationID: '50000162',
    Language: 'MS',
    GENVARIANT: 'MX-MSDS',
    ProductName: 'Rugby 200 SC',
    ChemicalName: '',
    CommonName: '',
    TradeName: 'Rugby 200 SC',
    CasNumber: '',
    CommercialNames: '',
    CMR: '',
    PublishDate: '04-16-18',
    ActiveVersion: '1',
    IUPAC: '',
    INCODE: '',
    EHSVersionNo: '',
    FMCBusiness: 'FMC',
    FileFormat: 'PDF',
    ValidityArea: '',
    ValidityAreaDescription: '',
    LegacySpecID: '6044-MX-A',
    LegacySDSID: '6044-MX-A',
    RevisionDate: '04-12-18',
    WercsRevisionNo: '1',
    WercsSubFormat: 'AGHS',
    AuthorizedPortal: 'EXTERNAL',
    Path: '\\\\NAH-S060\\BPMExtract'
  }
];
